<a href="https://colab.research.google.com/github/hdtruong802/Pytorch-Assignments/blob/main/%5BNLP%5DPart1_Build_Vocabulary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dự án thực hành: Phần 1 - Xây dựng bộ từ điển từ văn bản lớn
```
ProtonX - Pytorch Class
```

### Hướng dẫn làm bài
- Trong bài tập này bạn sẽ sử dụng Python 3.
- Sau khi bạn viết Code của mình xong, hãy chạy dòng Code đó để xem kết quả bên dưới.

### [Quan trọng] Chú ý
- **Không sử dụng hàm `input()` tại bất kỳ dòng lệnh nào**
- **Không thay đổi dòng code return của hàm**

Các bạn sẽ thực hiện `code` trong các phần hiển thị `#TODO: Lập trình tại đây` và thay thế các vị trí `None`. Có những câu hỏi chỉ cần trả về đáp án.

Sau khi viết xong Code của bạn, bạn hãy ấn "SHIFT"+"ENTER" để thực hiện chạy lệnh của Cell đó.

---
Điểm số:
* 10 điểm / Câu

Tiêu chí chấm điểm:
* Các bài tập sẽ được chấm dựa trên các Test-case.
* Các bạn không khởi tạo lại giá trị đầu vào bên trong hàm. Có thể khởi tạo các giá trị này ngoài hàm nhằm mục đích kiểm thử.

**Cài đặt bộ tokenizer bên thứ 3**

Xem thêm về các bộ tách từ xây dựng bằng [Spacy](https://protonx.io/courses/6523788337e7f90012890145/topics/6571b351e5bfd8001a8f0d50).

In [ ]:
!pip install pyvi
from spacy.lang.vi import Vietnamese

Thử tokenizer này

In [ ]:
nlp = Vietnamese()
tokens = nlp('Lớp học Pytorch là lớp học rất hay ho')

In [ ]:
tokens

Lớp học Pytorch là lớp học rất hay ho

Lặp qua các đơn vị lưu trữ trong Vocab dưới dạng từ vựng (Lexeme). Một từ vựng có các thuộc tính sau:

In [ ]:
for word in tokens:
    lexeme = tokens.vocab[word.text]
    print(lexeme.text, lexeme.orth, lexeme.shape_, lexeme.prefix_, lexeme.suffix_,
            lexeme.is_alpha, lexeme.is_digit, lexeme.is_title, lexeme.lang_)

Lớp học 9560392879819997953 Xxx xxx L học False False False vi
Pytorch 16295890598922194816 Xxxxx P rch True False True vi
là 12844001651356581174 xx l là True False False vi
lớp học 16939850666758009144 xxx xxx l học False False False vi
rất 1932685823275808203 xxx r rất True False False vi
hay ho 3393752619603724165 xxx xx h  ho False False False vi


- Văn bản: Văn bản gốc của từ vựng.

- Orth: Giá trị băm của từ vựng.

- Shape: Hình dạng từ ngữ trừu tượng của từ vựng.

- Prefix: Theo mặc định, là chữ cái đầu tiên của chuỗi từ.

- Suffix: Theo mặc định, là ba chữ cái cuối cùng của chuỗi từ.

- is alpha: Liệu từ vựng có bao gồm các ký tự chữ cái không?

- is digit: Liệu từ vựng có bao gồm các chữ số không?

Tải dữ liệu wiki

Bạn hãy tải dữ liệu Wiki [tại đây](https://drive.google.com/file/d/1f0yEMqH7U5v4uhGHcRHxRWUhOndV9xkn/view?usp=drive_link) và upload lên Colab

Phân tích: Có rất nhiều câu ngắn trong dữ liệu vì thế bạn hãy lọc những câu có chiều dài ngắn hơn 10 từ và tiến hành tách token

In [ ]:
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from collections import Counter
import io

def count_tokens_in_file(filepath, min_length):
    """
    Hàm này đọc một tệp tin văn bản và đếm số lượng xuất hiện của từng token.
    Chỉ xử lý các câu có chiều dài lớn hơn hoặc bằng min_length.

    Args:
    filepath: Đường dẫn đến tệp tin văn bản.
    min_length: Độ dài tối thiểu của câu để được xử lý.

    Returns:
    Counter object với số lượng xuất hiện của mỗi token.
    """

    # TODO 1: Bộ đếm token và số lượng xuất hiện
    counter = Counter()
    # Mở File
    with io.open(filepath, encoding="utf8") as f:
        for string_ in f:
            # TODO 2: Chỉ làm việc với những câu có chiều dài lớn hơn hoặc bằng min_length
            if len(string_) >= min_length:
              # Tiến hành tách token
              doc = set(string_.replace("\n","").replace(",","").replace('"',"").replace(".","").split(" "))
              # TODO 3: Update counter với bộ đếm
              counter.update(doc)
    return counter

# Sử dụng hàm
filepath = '/content/drive/My Drive/wiki_part1.txt'
min_length = 10
# TODO 4: Dùng hàm count_tokens_in_file để build counter
counter = count_tokens_in_file(filepath, min_length)

Cài đặt các ký tự đặc biệt:

In [ ]:
# Token không có
unk_token = '<unk>'
# Token để padding
pad_token = '<pad>'
# Token bắt đầu câu
bos_token = '<bos>'
# Token kết thúc câu
eos_token = '<eos>'

from torchtext.vocab import vocab
# TODO 5: Xây dựng Vocab bằng Pytorch
torchVocab = vocab(counter, specials=[unk_token, pad_token, bos_token, eos_token])

Test Code

In [ ]:
def test_initialization():
    try:
        assert unk_token in torchVocab.get_stoi()
        assert pad_token in torchVocab.get_stoi()
        assert bos_token in torchVocab.get_stoi()
        assert eos_token in torchVocab.get_stoi()
        print("Test Initialization: Passed")
    except AssertionError:
        print("Test Initialization: Failed")

def test_special_tokens():
    try:
        for token in [unk_token, pad_token, bos_token, eos_token]:
            assert token in torchVocab.get_stoi()
        print("Test Special Tokens: Passed")
    except AssertionError:
        print("Test Special Tokens: Failed")

def test_token_to_index():
    try:
        known_token = list(counter.keys())[0]
        assert torchVocab[known_token] == torchVocab.get_stoi()[known_token]
        assert torchVocab['<unk>'] == torchVocab.get_stoi()[str(unk_token)]
        print("Test Token to Index Conversion: Passed")
    except AssertionError:
        print("Test Token to Index Conversion: Failed")

def test_index_to_token():
    try:
        known_index = torchVocab.get_stoi()[list(counter.keys())[0]]
        assert torchVocab.get_itos()[known_index] == list(counter.keys())[0]
        print("Test Index to Token Conversion: Passed")
    except AssertionError:
        print("Test Index to Token Conversion: Failed")

def test_vocabulary_size():
    try:
        expected_size = len(counter) + 4  # 4 for the special tokens
        assert len(torchVocab) == expected_size
        print("Test Vocabulary Size: Passed")
    except AssertionError:
        print("Test Vocabulary Size: Failed")

def test_unknown_token_handling():
    try:
        assert torchVocab['<unk>'] == torchVocab.get_stoi()[unk_token]
        print("Test Handling of Unknown Tokens: Passed")
    except AssertionError:
        print("Test Handling of Unknown Tokens: Failed")


test_initialization()
test_special_tokens()
test_token_to_index()
test_index_to_token()
test_vocabulary_size()
test_unknown_token_handling()


Test Initialization: Passed
Test Special Tokens: Passed
Test Token to Index Conversion: Passed
Test Index to Token Conversion: Passed
Test Vocabulary Size: Passed
Test Handling of Unknown Tokens: Passed


**Kết quả mong đợi:**

```
Test Initialization: Passed
Test Special Tokens: Passed
Test Token to Index Conversion: Passed
Test Index to Token Conversion: Passed
Test Vocabulary Size: Passed
Test Handling of Unknown Tokens: Passed
```



In [ ]:
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
BATCH_SIZE = 4
PAD_IDX = torchVocab['<pad>']
BOS_IDX = torchVocab['<bos>']
EOS_IDX = torchVocab['<eos>']

### Lập trình hàm cắt một chuỗi thành nhiều chuỗi nhỏ

Hàm `trim_sequence_to_parts` có chức năng chia một chuỗi (hoặc một dãy các phần tử) thành nhiều phần nhỏ với độ dài xác định. Dưới đây là mô tả chi tiết về các đối số đầu vào và giá trị trả về của hàm này:

**Đối số:**
1. `sequence`: Đây là chuỗi hoặc dãy các phần tử cần được chia nhỏ. Đối số này có thể là một chuỗi các ký tự, một danh sách, hoặc bất kỳ đối tượng nào khác có thể được lặp qua (iterable).
2. `part_length`: Đây là độ dài của từng phần sau khi chia. Đối số này phải là một số nguyên, chỉ ra số lượng phần tử tối đa trong mỗi phần nhỏ sau khi chia.

**Chức năng của Hàm:**
- Hàm `trim_sequence_to_parts` lặp qua `sequence` và chia nó thành các phần nhỏ, mỗi phần có độ dài không vượt quá `part_length`.
- Việc chia này được thực hiện bằng cách sử dụng list comprehension, một cấu trúc ngắn gọn trong Python để tạo ra các danh sách mới.

**Giá trị trả về:**
- Hàm trả về một danh sách mới, trong đó mỗi phần tử là một phần của `sequence` với độ dài không vượt quá `part_length`.
- Nếu `sequence` không thể chia đều cho `part_length`, phần cuối cùng của danh sách trả về có thể sẽ ngắn hơn.

**Ví dụ:**
Nếu bạn gọi `trim_sequence_to_parts([1, 2, 3, 4, 5, 6, 7], 3)`, hàm sẽ trả về `[[1, 2, 3], [4, 5, 6], [7]]`. Trong ví dụ này, chuỗi `[1, 2, 3, 4, 5, 6, 7]` được chia thành các phần, mỗi phần có 3 phần tử, trừ phần cuối cùng chỉ có 1 phần tử.

In [ ]:
max_length = 30
def trim_sequence_to_parts(sequence, part_length):
    # TODO 6: Lập trình tại đây
    result = []
    for i in range(0, len(sequence), part_length):
        result.append(sequence[i:i+part_length])
    return result

In [ ]:
trim_sequence_to_parts([1, 2, 3, 4, 5, 6, 7], 3)

[[1, 2, 3], [4, 5, 6], [7]]

### Lập trình hàm xử lý dữ liệu

Hàm `data_process` là một hàm dùng để xử lý dữ liệu văn bản từ một tệp tin và chuyển đổi chúng thành dạng tensor sử dụng một từ điển (vocab). Dưới đây là mô tả chi tiết về các đối số và giá trị trả về của hàm này:

**Đối số:**
1. `filepath`: Đường dẫn đến tệp tin chứa dữ liệu văn bản cần xử lý. Đây là một chuỗi ký tự (string) chỉ ra vị trí của tệp tin trong hệ thống tập tin.
2. `vocab`: Một từ điển hoặc cấu trúc dữ liệu tương tự, dùng để chuyển đổi từ các token văn bản sang số nguyên (index). Mỗi token trong văn bản sẽ được tìm kiếm trong `vocab` để lấy chỉ số tương ứng.
3. `min_length`: Độ dài tối thiểu của một chuỗi ký tự (câu) để nó được xem xét và xử lý. Nếu một chuỗi ngắn hơn `min_length`, nó sẽ bị bỏ qua.
4. `max_length`: Độ dài tối đa cho phép của một chuỗi tensor sau khi được chia nhỏ bằng hàm `trim_sequence_to_parts`.

**Chức năng của Hàm:**
- Hàm mở tệp tin văn bản tại `filepath` sử dụng mã hóa UTF-8.
- Đọc từng dòng trong tệp tin. Mỗi dòng được coi như một chuỗi ký tự (`string_`).
- Nếu độ dài của `string_` (tính theo số lượng từ) lớn hơn hoặc bằng `min_length`, chuỗi sẽ được xử lý tiếp:
    - Sử dụng một hàm nlp như trên để xử lý chuỗi ký tự này, tạo ra một đối tượng (có thể là một danh sách các token).
    - Mỗi token trong đối tượng này được chuyển đổi thành số nguyên (index) sử dụng `vocab`. Kết quả là một tensor PyTorch (`vi_tensor_`).
    - Tensor này sau đó được chia thành nhiều phần nhỏ hơn với độ dài tối đa là `max_length` sử dụng hàm `trim_sequence_to_parts`.
    - Mỗi phần nhỏ này được thêm vào danh sách `data`.

**Giá trị trả về:**
- Hàm trả về `data`, là một danh sách các phần tensor. Mỗi phần tensor đại diện cho một phần của dữ liệu văn bản, đã được chuyển đổi thành dạng số nguyên và chia theo độ dài tối đa xác định.



In [ ]:
import traceback

def data_process(filepath, vocab, min_length, max_length):
    data = []
    # TODO 7: Lập trình tại đây
    try:
      with open(filepath, 'r', encoding="utf8") as f:
        for string_ in f:
          string_ = string_.strip()
          tokens = [token for token in string_.split() if token]
          if len(tokens) >= min_length:
            # Chuyển đổi token thành index sử dụng vocab
            indexes = [vocab[token] for token in tokens if token in vocab]
            # Tạo tensor PyTorch từ các index
            vi_tensor_ = torch.tensor(indexes, dtype=torch.long)
            # Chia tensor thành các phần nhỏ hơn với độ dài tối đa là max_length
            parts = trim_sequence_to_parts(vi_tensor_, max_length)
            # Thêm các phần nhỏ vào danh sách data
            data.extend(parts)
    except Exception as e:
      traceback.print_exc()
    return data

In [ ]:
train_data = data_process(filepath, torchVocab, 10, 30)

Test Code

In [ ]:
%%writefile test.txt
Những gì bạn sẽ học được từ lớp học này

Hiểu cách các mô hình học sâu hoạt động

Triển khai các model tiên tiến nhất với Pytorch bao gồm thị giác máy tính và xử lý ngôn ngữ tự nhiên

Cách làm việc với nhiều loại dữ liệu khác nhau để xây dựng model

Writing test.txt


In [ ]:
file_test_path = 'test.txt'
test_counter = count_tokens_in_file(file_test_path, min_length)
testVocab = vocab(test_counter, specials=[unk_token, pad_token , bos_token, eos_token])
test_data = data_process(file_test_path, testVocab, 10, 30)

In [ ]:
test_counter

Counter({'sẽ': 1,
         'bạn': 1,
         'này': 1,
         'được': 1,
         'gì': 1,
         'Những': 1,
         'từ': 1,
         'lớp': 1,
         'học': 2,
         'sâu': 1,
         'mô': 1,
         'Hiểu': 1,
         'các': 2,
         'cách': 1,
         'hoạt': 1,
         'hình': 1,
         'động': 1,
         'bao': 1,
         'gồm': 1,
         'model': 2,
         'nhất': 1,
         'lý': 1,
         'khai': 1,
         'nhiên': 1,
         'tính': 1,
         'thị': 1,
         'giác': 1,
         'ngôn': 1,
         'Triển': 1,
         'Pytorch': 1,
         'và': 1,
         'tự': 1,
         'tiến': 1,
         'ngữ': 1,
         'máy': 1,
         'với': 2,
         'xử': 1,
         'tiên': 1,
         'dữ': 1,
         'nhiều': 1,
         'làm': 1,
         'loại': 1,
         'liệu': 1,
         'khác': 1,
         'Cách': 1,
         'để': 1,
         'việc': 1,
         'dựng': 1,
         'nhau': 1,
         'xây': 1})

In [ ]:
test_data

[tensor([ 9,  8,  5,  4, 12,  7, 10, 11, 12,  6]),
 tensor([32, 26, 16, 23, 41, 36, 24, 39, 33, 21, 22, 29, 30, 38, 28, 34, 40, 25,
         31, 37, 35, 27]),
 tensor([48, 44, 50, 39, 43, 45, 42, 46, 47, 52, 49, 53, 51, 23])]

Kết quả mong đợi

```python
[tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13]),
 tensor([13]),
 tensor([14, 15, 16, 17, 18, 19, 13]),
 tensor([13]),
 tensor([20, 16, 21, 22, 23, 24, 25, 26, 27, 28]),
 tensor([29, 30, 31, 32, 13]),
 tensor([13]),
 tensor([33, 34, 24, 35, 36, 37, 38, 39, 40, 41]),
 tensor([21, 13])]
```

In [ ]:
BATCH_SIZE = 4
PAD_IDX = torchVocab['<pad>']
BOS_IDX = torchVocab['<bos>']
EOS_IDX = torchVocab['<eos>']

### Lập trình hàm chia batch

Hàm `generate_batch` là một hàm được thiết kế để xử lý các batch dữ liệu (batch) và chuẩn bị chúng để có thể được sử dụng trong các mô hình học máy, đặc biệt là trong xử lý ngôn ngữ tự nhiên. Dưới đây là mô tả chi tiết về các đối số và giá trị trả về của hàm này:

**Đối số:**
1. `data_batch`: Một batch dữ liệu, thường là một danh sách các tensor. Mỗi tensor trong `data_batch` đại diện cho một mẫu dữ liệu (ví dụ, một câu hoặc đoạn văn).

**Chức năng của Hàm:**
- Hàm lặp qua mỗi mẫu dữ liệu (`vi_item`) trong `data_batch`.
- Đối với mỗi `vi_item`:
  - Tạo một tensor `pads` chứa các giá trị padding (PAD_IDX) với kích thước sao cho tổng chiều dài của `vi_item` sau khi thêm các giá trị padding sẽ bằng `max_length`.
  - Sử dụng hàm `torch.cat` để ghép `vi_item` với các giá trị BOS_IDX (đánh dấu bắt đầu của chuỗi), EOS_IDX (đánh dấu kết thúc của chuỗi), và tensor `pads` chứa các giá trị padding.
  - Thêm `vi_item` đã được xử lý vào danh sách `vi_batch`.
- Cuối cùng, sử dụng hàm `pad_sequence` để chuẩn hóa kích thước của tất cả các mẫu trong `vi_batch`, đảm bảo rằng tất cả chúng có chiều dài như nhau bằng cách thêm các giá trị padding (PAD_IDX) ở cuối nếu cần.

**Giá trị trả về:**
- Hàm trả về `vi_batch`, là một tensor đã được chuẩn hóa về kích thước, với mỗi mẫu dữ liệu trong batch đều có cùng chiều dài `max_length`.


In [ ]:
from torch.nn.utils.rnn import pad_sequence

def generate_batch(data_batch):
  vi_batch = []
  # TODO 8: Lập trình tại đây
  for vi_item in data_batch:
    #Tạo một tensor pads chứa các giá trị padding (PAD_IDX)
    pads = torch.full((max_length - len(vi_item),), PAD_IDX, dtype=torch.long)
    #Sử dụng hàm torch.cat để ghép vi_item với các giá trị BOS_IDX (đánh dấu bắt đầu của chuỗi), EOS_IDX (đánh dấu kết thúc của chuỗi), và tensor pads chứa các giá trị padding.
    vi_item = torch.cat([torch.tensor([BOS_IDX]), vi_item, torch.tensor([EOS_IDX]), pads])
    #Thêm vi_item đã được xử lý vào danh sách vi_batch.
    vi_batch.append(vi_item)
  #Chuẩn hóa tất cả các mẫu
  vi_batch = pad_sequence(vi_batch, batch_first=True, padding_value=PAD_IDX)
  return vi_batch

Test Code

In [ ]:
def test_generate_batch():
    try:
        # Test Case 1: Single item in data_batch
        data_batch = [torch.tensor([3, 4, 5])]
        batch = generate_batch(data_batch)
        assert batch.shape == (1, 32), "Failed: Shape mismatch in single item test"

        # Test Case 2: Multiple items in data_batch of different lengths
        data_batch = [torch.tensor([3, 4, 5]), torch.tensor([6, 7])]
        batch = generate_batch(data_batch)
        assert batch.shape == (2, 32), "Failed: Shape mismatch in multiple items test"

        # Test Case 3: Check if BOS_IDX and EOS_IDX are added correctly
        data_batch = [torch.tensor([3])]
        batch = generate_batch(data_batch)
        assert batch[0][0] == BOS_IDX and batch[0][2] == EOS_IDX, "Failed: BOS_IDX or EOS_IDX missing"

        print("All tests passed.")
    except AssertionError as e:
        print(e)

# Run the tests
test_generate_batch()


All tests passed.


**Kết quả mong đợi:**

All tests passed.


In [ ]:
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import DataLoader
test_iter = DataLoader(test_data, batch_size=4,
                        shuffle=True, collate_fn=generate_batch)
for item in test_iter:
    print('Chiều: ', item.shape)
    print('Giá trị')
    print(item)

Chiều:  torch.Size([3, 32])
Giá trị
tensor([[ 2,  9,  8,  5,  4, 12,  7, 10, 11, 12,  6,  3,  1,  1,  1,  1,  1,  1,
          1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2, 32, 26, 16, 23, 41, 36, 24, 39, 33, 21, 22, 29, 30, 38, 28, 34, 40,
         25, 31, 37, 35, 27,  3,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2, 48, 44, 50, 39, 43, 45, 42, 46, 47, 52, 49, 53, 51, 23,  3,  1,  1,
          1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])


**Kết quả mong đợi:**



```
Chiều:  torch.Size([4, 32])
Giá trị
tensor([[ 2, 14, 15, 16, 17, 18, 19, 13,  3,  1,  1,  1,  1,  1,  1,  1,  1,  1,
          1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2, 13,  3,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
          1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2, 20, 16, 21, 22, 23, 24, 25, 26, 27, 28,  3,  1,  1,  1,  1,  1,  1,
          1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,  3,  1,  1,  1,  1,  1,  1,
          1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])
Chiều:  torch.Size([4, 32])
Giá trị
tensor([[ 2, 21, 13,  3,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
          1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2, 29, 30, 31, 32, 13,  3,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
          1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2, 13,  3,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
          1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2, 13,  3,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
          1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])
Chiều:  torch.Size([1, 32])
Giá trị
tensor([[ 2, 33, 34, 24, 35, 36, 37, 38, 39, 40, 41,  3,  1,  1,  1,  1,  1,  1,
          1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])
```



Thực hiện build trên bộ wiki lớn

In [ ]:
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import DataLoader
train_iter = DataLoader(train_data, batch_size=8,
                        shuffle=True, collate_fn=generate_batch)

# for item in train_iter:
#     print('Chiều: ', item.shape)
#     print('Giá trị')
#     print(item)

Save vocab

In [ ]:
torch.save(torchVocab, 'wikiVocab.pth')

Load vocab

In [ ]:
torchVocab = torch.load('wikiVocab.pth')

In [ ]:
# Lấy danh sách các phương thức của đối tượng Vocab
vocab_methods = [method for method in dir(torchVocab) if callable(getattr(torchVocab, method))]

# In ra các phương thức của đối tượng Vocab
print("Các phương thức của đối tượng Vocab:")
for method in vocab_methods:
    print(method)

# Lấy danh sách các thuộc tính của đối tượng Vocab
vocab_attributes = [attribute for attribute in dir(torchVocab) if not callable(getattr(torchVocab, attribute))]

# In ra các thuộc tính của đối tượng Vocab
print("Các thuộc tính của đối tượng Vocab:")
for attribute in vocab_attributes:
    print(attribute)


Các phương thức của đối tượng Vocab:
__call__
__class__
__contains__
__delattr__
__dir__
__eq__
__format__
__ge__
__getattr__
__getattribute__
__getitem__
__getstate__
__gt__
__hash__
__init__
__init_subclass__
__le__
__len__
__lt__
__ne__
__new__
__prepare_scriptable__
__reduce__
__reduce_ex__
__repr__
__setattr__
__setstate__
__sizeof__
__str__
__subclasshook__
_apply
_call_impl
_get_backward_hooks
_get_backward_pre_hooks
_get_name
_load_from_state_dict
_maybe_warn_non_full_backward_hook
_named_members
_register_load_state_dict_pre_hook
_register_state_dict_hook
_replicate_for_data_parallel
_save_to_state_dict
_slow_forward
_wrapped_call_impl
add_module
append_token
apply
bfloat16
buffers
children
compile
cpu
cuda
double
eval
extra_repr
float
forward
get_buffer
get_default_index
get_extra_state
get_itos
get_parameter
get_stoi
get_submodule
half
insert_token
ipu
load_state_dict
lookup_indices
lookup_token
lookup_tokens
modules
named_buffers
named_children
named_modules
named_parameter